"""book table

Revision ID: 33b7e5d7c1c7
Revises: 
Create Date: 2022-03-22 13:35:33.965195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b7e5d7c1c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('chapter_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_id'), 'chapter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_id'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
